"""empty message

Revision ID: 5dbddfc15686
Revises: 2dbda51da632
Create Date: 2021-01-17 20:31:23.575357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5dbddfc15686'
down_revision = '2dbda51da632'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('created_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'created_at')
    # ### end Alembic commands ###
