"""empty message

Revision ID: 8a58c05a503a
Revises: 5dbddfc15686
Create Date: 2021-01-17 20:32:42.679567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a58c05a503a'
down_revision = '5dbddfc15686'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'payoff')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('payoff', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
