"""test

Revision ID: b4957c1b41b9
Revises: 2ad8aaf1e5f2
Create Date: 2021-01-07 16:56:21.183504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4957c1b41b9'
down_revision = '2ad8aaf1e5f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('test', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'test')
    # ### end Alembic commands ###
